- name: download artifact
  get_url:
     url: https://github.com/Anji399/fibon/raw/master/target/fibon.war
     dest: /tmp
- name: copy artifact
  copy:
     src: /tmp/fibon.war
     dest: /opt/tomcat/webapps/fibon.war
     owner: tomcat
     group: tomcat
     remote_src: yes
  notify: restart tomcat
 
